--Lunaris

require("prototypes.lunaris.planet.planet")
require("prototypes.lunaris.autoplace-controls")
require("prototypes.lunaris.resources")
require("prototypes.lunaris.items")
require("prototypes.lunaris.technology")
require("prototypes.lunaris.tile.tiles")
require("prototypes.lunaris.tile.tile-collision-masks")
require("prototypes.lunaris.tile.tile-graphics")
require("prototypes.lunaris.tile.tile-pollution-values")
require("prototypes.lunaris.tile.tile-sounds")
require("prototypes.lunaris.tile.tile-trigger-effects")
require("prototypes.lunaris.item-groups")
require("prototypes.lunaris.decorative.decoratives")
require("prototypes.lunaris.decorative.decorative-trigger-effects")
require("prototypes.lunaris.entity.entity-util")
require("prototypes.lunaris.noise-expressions")
require("prototypes.lunaris.entity.entities")
require("prototypes.lunaris.noise-programs")
require("prototypes.lunaris.entity.plants")
require("prototypes.lunaris.entity.hit-effects")
require("prototypes.lunaris.entity.enemy-projectiles")
require("prototypes.lunaris.entity.enemies")
require("prototypes.lunaris.entity.enemy-autoplace-utils")
require("prototypes.lunaris.entity.enemy-constants")
require("prototypes.lunaris.entity.spawner-animation")
require("prototypes.lunaris.entity.spitter-animations")
require("prototypes.lunaris.entity.biter-ai-settings")
require("prototypes.lunaris.entity.worm-animations")
require("prototypes.lunaris.entity.biter-animations")
require("prototypes.lunaris.entity.biter-die-effects")
require("prototypes.lunaris.entity.turrets")
require("prototypes.lunaris.entity.assemblerpipes")
require("prototypes.lunaris.entity.pipecovers")
require("prototypes.lunaris.factoriopedia-simulations")
require("prototypes.lunaris.particles")
require("prototypes.lunaris.particle-animations")


--Crystara

--require("prototypes.crystara.planet.planet")
--require("prototypes.crystara.autoplace-controls")
--require("prototypes.crystara.resources")
--require("prototypes.crystara.items")
--require("prototypes.crystara.technology")

--Crymora

require("prototypes.crymora.planet.planet")
require("prototypes.crymora.autoplace-controls")
require("prototypes.crymora.resources")
require("prototypes.crymora.items")
require("prototypes.crymora.technology")